<?php

namespace App\Http\Requests\Api\V1\Clinic;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreArticleRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user('clinic') !== null;
    }

    public function rules(): array
    {
        return [
            'title'            => ['required', 'string', 'max:255'],
            // slug is auto-generated by Article::booted() if omitted; still unique when provided.
            'slug'             => ['nullable', 'string', 'max:255', 'unique:articles,slug'],
            'body'             => ['required', 'string'],
            'meta_description' => ['nullable', 'string', 'max:300'],
            'cover_image'      => ['nullable', 'string'],
            'tags'             => ['nullable', 'array'],
            'tags.*'           => ['string'],
            'is_published'     => ['nullable', 'boolean'],
        ];
    }
}
