<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Phase 2 augments the Phase-1 log table:
 *
 *  - response_ms     — captured by the interceptor for the "avg response
 *                      time per provider" chart.
 *  - conversation_id — uuid that groups consecutive turns by the same
 *                      user/visitor within a 30-minute sliding window
 *                      into one "conversation" thread. Computed at write
 *                      time; backfilled for existing rows by a follow-up
 *                      data migration (DataBackfill seeder).
 *
 * And creates `ai_user_interaction_summaries` — the table the
 * SummarizeUserInteractionJob writes to after each authenticated chat.
 * Phase 2 ships with seeded fake summaries so the user-profile section
 * has data the moment the page loads; the live job is a stub that the
 * super-admin can wire up to the real LLM when ready (it's gated behind
 * the existing ai_freeform_enabled setting).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('ai_assistant_logs', function (Blueprint $table) {
            $table->unsignedInteger('response_ms')->nullable()->after('tokens_out');
            $table->uuid('conversation_id')->nullable()->after('guard');

            $table->index('conversation_id');
        });

        Schema::create('ai_user_interaction_summaries', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            // The originating log (last turn of the thread). Useful for
            // "open the original conversation" from the user profile.
            $table->foreignId('log_id')->nullable()->constrained('ai_assistant_logs')->nullOnDelete();

            // Short human summary (1–2 sentences). Generated by the LLM
            // when the live job runs; faked at seed time for Phase 2.
            $table->text('topic');

            // Aggregated context — the categories/clinics surfaced
            // across the thread, captured as ids so the UI can link to
            // their admin pages without another lookup.
            $table->json('categories')->nullable();
            $table->json('clinics')->nullable();

            // Discrete intent bucket — drives the colored badge on the
            // user profile timeline.
            $table->enum('seriousness', ['exploration', 'comparing', 'near_decision'])
                ->default('exploration');

            $table->string('model_used', 64)->nullable();
            $table->timestamp('generated_at')->nullable();
            $table->timestamps();

            $table->index(['user_id', 'generated_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('ai_user_interaction_summaries');

        Schema::table('ai_assistant_logs', function (Blueprint $table) {
            $table->dropIndex(['conversation_id']);
            $table->dropColumn(['response_ms', 'conversation_id']);
        });
    }
};
